name: movie_posters
description: MovieWalls - Cinematic Wallpapers App
publish_to: 'none'
version: 10.2.25+2

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # HTTP & Web Scraping
  dio: ^5.4.0
  html: ^0.15.4

  # Local Storage
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  shared_preferences: ^2.2.2

  # Image Handling
  cached_network_image: ^3.3.1
  image: ^4.1.7
  flutter_cache_manager: ^3.3.1
  photo_view: ^0.14.0

  # UI Components
  flutter_staggered_grid_view: ^0.7.0
  shimmer: ^3.0.0
  carousel_slider: ^5.0.0
  smooth_page_indicator: ^1.1.0
  flutter_svg: ^2.0.9

  # Monetization
  google_mobile_ads: ^5.0.0
  in_app_purchase: ^3.1.13

  # Utilities
  permission_handler: ^12.0.1
  share_plus: ^7.2.1
  url_launcher: ^6.2.4
  path_provider: ^2.1.2
  package_info_plus: ^9.0.0
  device_info_plus: ^9.1.0
  in_app_review: ^2.0.8

  # Wallpaper Setting
  flutter_wallpaper_manager: ^0.0.3
  async_wallpaper: ^2.1.0

  # Responsive Design
  flutter_screenutil: ^5.9.0

  # Performance
  visibility_detector: ^0.4.0+2
  
  # Networking
  connectivity_plus: ^5.0.2

  # Other
  intl: ^0.19.0
  equatable: ^2.0.5
  dartz: ^0.10.1
  logger: ^2.0.2+1

  flutter_inappwebview: ^6.1.5
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
  build_runner: ^2.4.8
  riverpod_generator: ^2.3.11
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  flutter_launcher_icons: ^0.14.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/
    - assets/icons/
    - assets/lottie/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/moviewalls.png"
  min_sdk_android: 24
  adaptive_icon_background: "#000000"
  adaptive_icon_foreground: "assets/images/moviewalls.png"

